### ISSUE TITLE
Probelm with Horde_Core_ActiveSync_Driver::authenticate not calling parent method

### ISSUE THREAD

**Issue by midahp** [maintaina-com/Core#26]
With the commit [53f0ab007e0fbf80a2350fc995815253d95b7fd5](https://github.com/maintaina-com/Core/commit/53f0ab007e0fbf80a2350fc995815253d95b7fd5#diff-cfd56bada1310bfabd2406fe937d79500f3acc108fce8ad3df7acafa9a78dcb0) the core driver returns true before calling the parent authenticate method. 

The parent method sets the `_authUser` and `_authPass` properties. `_authUser` is needed for https://github.com/maintaina-com/ActiveSync/blob/FRAMEWORK_6_0/lib/Horde/ActiveSync/Driver/Base.php#L197

There are many ways to fix this:
1. remove the line
2. replace it with `return parent::authenticate($username, $password, $domain);`
3. replace it with 
```
parent::authenticate($username, $password, $domain);
return true;
```
4. replace it with
```
$this->_authUser = $username;
$this->_authPass = $password;
return true;
```

Number 3 is probably the safest.

**Comment by ralflang** [comment]
@mrubinsk I think you are the better expert on this code... I will have a closer look tomorrow though.

**Comment by mrubinsk** [comment]
> @mrubinsk I think you are the better expert on this code... I will have a closer look tomorrow though.

Indeed. I'm not sure what the purpose of the `return true;` that was added there, but it's definitely short circuiting the rest of that method when "basic" authentication is successful. Without really looking to see why it was added, my suggestion would be to simply remove that line.
